### PR TITLE
Add examples from DeepMind paper (Learning explanatory rules from noisy data)

### PR DESCRIPTION
**Pull request by MystikNinja**
I've added the examples used in the paper by (Evans & Greffenstette, 2018). They are laid out in the paper in Appendix G. In most cases, it was a direct translation to code. In some cases, I filled in the blanks where details were unspecified.

### CODE REVIEW

**Comment by andrewcropper** [comment]
Excellent, thank you. I will look at merging this change into the main repository at the weekend.

Kind regards,

Andrew

**Comment by pmoura** [comment]
I'm porting these new examples to the Logtalk port of Metagol. Found two minor issues with the original code. The `member.pl` and `son.pl` report singleton variables. In `member.pl`, `R` is a singleton in the clause:

```
metarule([P,Q,R],([P,A,B]:-[[Q,B,C],[P,A,C]])).
```

In `son.pl`, `R` is a singleton in the clause:

```
metarule([P,Q,R],([P,A]:-[[Q,A,B]])).
```

It seems fine to replace these singleton variables with the anonymous variable. Do you agree?

**Comment by andrewcropper** [comment]
Hi Paulo,

Yes, those two variables can be changed to anonymous variable. Thank you for spotting them.

Kind regards,

Andrew

**Comment by pmoura** [comment]
Thanks for confirming. Do you have the BibTex record for the paper? I would like to add it to the port documentation and maybe also extract some unit tests from the paper if you can send me a PDF version.

**Comment by andrewcropper** [comment]
Here is the bibtex record:

https://dblp.uni-trier.de/rec/bib2/journals/jair/EvansG18.bib

and paper:

https://arxiv.org/pdf/1711.04574.pdf

**Comment by pmoura** [comment]
Thanks! Updated the port notes (https://github.com/LogtalkDotOrg/logtalk3/blob/master/ports/metagol/NOTES.md).

**Pull request merged**
